### ISSUE TITLE
Python 3 import error

### ISSUE THREAD

**Issue by hasanzabaak** [rushilsrivastava/image-scrapers#14]
Issue Template
=========================================
Stacktrace:
```
Traceback (most recent call last):
  File "/home/cabox/workspace/images/image_search/bin/image_search", line 9, in <module>
    load_entry_point('image-search==0.0.1', 'console_scripts', 'image_search')()
  File "/home/cabox/workspace/images/image_search/lib/python3.4/site-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/cabox/workspace/images/image_search/lib/python3.4/site-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/home/cabox/workspace/images/image_search/lib/python3.4/site-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/cabox/workspace/images/image_search/lib/python3.4/site-packages/image_search/console.py", line 5, in <module>
    import _bing
ImportError: No module named '_bing'
```
Running Python3.4, seems to be an import error.

**Comment by rushilsrivastava** [comment]
Hmm, interesting. I messed that up 😅. Will push some changes soon.
