### ISSUE TITLE
ModuleNotFoundError: No module named _bing

### ISSUE THREAD

**Issue by cdrakke** [rushilsrivastava/image-scrapers#16]
C:\Users\Calvi\Desktop>image_search google cat --limit 10 --json
Traceback (most recent call last):
  File "C:\Users\Calvi\AppData\Local\Programs\Python\Python38-32\Scripts\image_search-script.py", line 11, in <module>
    load_entry_point('image-search==0.0.1', 'console_scripts', 'image_search')()
  File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2855, in load_entry_point
    return ep.load()
  File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2446, in load
    return self.resolve()
  File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\calvi\appdata\local\programs\python\python38-32\lib\site-packages\image_search\console.py", line 5, in <module>
    import _bing
ModuleNotFoundError: No module named '_bing'

**Comment by rushilsrivastava** [comment]
Thanks for sharing, let me take a look at this. I haven't touched this library in a while.

**Comment by rushilsrivastava** [comment]
Hi @Calvindrakkez020! I haven't been able to reproduce this error from my end. Can you try reinstalling the library and letting me know?

**Comment by GitOffMyLAN** [comment]
I'm getting the same error on a fresh install. Reinstalling does not fix it.

Traceback (most recent call last):
  File "/usr/local/bin/image_search", line 11, in <module>
    load_entry_point('image-search==0.0.1', 'console_scripts', 'image_search')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/image_search/console.py", line 5, in <module>
    import _bing
ModuleNotFoundError: No module named '_bing'

**Comment by rushilsrivastava** [comment]
Thanks for the report @GitOffMyLAN, let me investigate this further. I haven't touched this library in over 2-years and I am opting to just completely rewrite it.

**Comment by kartikye** [comment]
I have this error too on windows.

**Comment by buyi1128** [comment]
ModuleNotFoundError: No module named '_bing', same error happens to me. how to solve it?

**Comment by buyi1128** [comment]
> ModuleNotFoundError: No module named '_bing', same error happens to me. how to solve it?
It happens when using 'pip install image_search'，instead of  using 'python setup.py install' will success.

**Comment by buyi1128** [comment]
This error happened using 'pip install image_search'.
using 'python setup.py install' will success.

**Comment by geriskenderi** [comment]
I also get the same error on windows when installing with pip

**Comment by onlyrohits** [comment]
Use pip install git+https://github.com/rushilsrivastava/image_search.git

**Comment by saitodisse** [comment]
> Use pip install git+https://github.com/rushilsrivastava/image_search.git

Thanks @onlyrohits, this worked fine for me
