### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by YHSot976** [rushilsrivastava/image-scrapers#2]
[%] Successfully launched Chrome Browser
[%] Successfully opened link.
[%] Scrolling down.
[%] Successfully clicked 'Show More Button'.
[%] Reached end of Page.
Traceback (most recent call last):
  File "google_scraper.py", line 120, in <module>
    source = search(url)
  File "google_scraper.py", line 55, in search
    f = open('dataset/logs/google/source.html', 'w+')
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/logs/google/source.html'

**Comment by rushilsrivastava** [comment]
Hi, thanks for reporting this. For some reason, when I released the latest code, I reordered the variables, resulting in the searching to be conducted before the folder structure is generated. This should be fixed now.

**Comment by YHSot976** [comment]
Sorry. It seems I have driver issue. Do you know where the problem is?

[%] Successfully launched Chrome Browser
[%] Successfully opened link.
[%] Scrolling down.
Traceback (most recent call last):
  File "google_scraper.py", line 129, in <module>
    source = search(url)
  File "google_scraper.py", line 43, in search
    browser.find_element_by_id("smb").click()
  File "/Users/Tristan/anaconda3/envs/image/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/Tristan/anaconda3/envs/image/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Users/Tristan/anaconda3/envs/image/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/Tristan/anaconda3/envs/image/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)

**Comment by YHSot976** [comment]
Sorry, I'm really noob in this. But it seems 
`browser.find_element_by_id("smb").click()`
gave the trouble. 
The show more button could be the problem. There is no button, so it's invisible and gave error.

**Comment by rushilsrivastava** [comment]
Hi,

`browser.find_element_by_id("smb").click()` is the "Show More Button". That generally always exists. What is your search term? 

I ran the example, and it worked perfectly fine:

    python3.5 google_scraper.py "https://www.google.com/search?q=cats&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiCi-3ygMPZAhVJ2GMKHcIJBNYQ_AUICigB&biw=1825&bih=940"

**Comment by YHSot976** [comment]
The "cats" work for me as well. Can you try "one does not simply meme"?

**Comment by rushilsrivastava** [comment]
I went ahead and committed a fix. I had no idea that there were searches with no "Show More Button".
